### ISSUE TITLE
SimDag seems to ignore tasks if it has more that 100 runnable task on the same host 

### ISSUE THREAD

**Issue by aliomarabdelazim** [simgrid/simgrid#122]
Hi, 
I have a code, that simulates a multicore system, based on your help and suggestions previously provided, I am using "cpu/model" value="Cas01">, "network/model" value="IB", and "host/model" value="compound"> 

the problem is now, If I have more than 100 task with status "runnable" and scheduled to the same host ... all tasks from 0 to 99 get executed and finish, while tasks 100 and above just get ignored, meaning that simulation finishes without these tasks report that they are finished, if you specifically wait till the finish time of a task > 100 is anything other than -1, simulation will run forever. 

And after the simulation finishes, tasks > 100 will have status 8 ..which is running, and finish time -1, even if all tasks are of the same length and all started on the same time, and on the same host, so they should finish together, however this does not happen for tasks > 100, 
I have attached sample code to reproduce the problem, I running SimGrid 3.13.4 on mac. 
run the code with parameters "./simulator platform.xml 101 101"

Thank you very much, I really appreciate your support
[multicore_scheduling.zip](https://github.com/simgrid/simgrid/files/548233/multicore_scheduling.zip)

**Comment by adegomme** [comment]
Hello, 
There is a setting in the development version to increase this value, as this issue was brought to us recently. Sadly this is not backported on the 3.13.x version, only on the 3.14-dev/3.13.90. If you are on the git master, you can increase the maxmin/concurrency_limit setting to set this value to a higher one (by adding --cfg=maxmin/concurrency_limit:1000 to your command line, for example). This should help in your case.

If you want to stick to the 3.13 version but you can change the sources, you can modify the   sg_concurrency_limit value in src/surf/maxmin.cpp or try to apply https://github.com/simgrid/simgrid/commit/b0873fb942f5d028c07216e2e5af2ab4924ccdf2


Best regards,
Augustin

**Comment by aliomarabdelazim** [comment]
Thank you for your support, is there any information when will SimGrid 3.14 be released ?

**Comment by mquinson** [comment]
I plan to release SimGrid 3.14 in 4 days.

**Comment by mquinson** [comment]
3.14 was released a few months ago. Thus closing. Thanks for reporting.
