### ISSUE TITLE
Suspending an execution does not seem to work

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#123]
Hello,

I just extended a bit the lazy process example so that we also test suspending an execution.
The bad news is that it does not work. The execution continues to progress while it's suspended:

```
examples/msg$ ./process-suspend/process-suspend ../platforms/small_platform.xml
[Boivin:Lazy:(2) 35.000000] [msg_process_suspend/INFO] Ok, let's do some work, then (for 10 sec on Boivin).
[Boivin:dream_master:(1) 37.000000] [msg_process_suspend/INFO] Give a 2 seconds break to the lazy guy while he's working...
[Boivin:dream_master:(1) 39.000000] [msg_process_suspend/INFO] Back to work, lazy guy!
[Boivin:dream_master:(1) 39.000000] [msg_process_suspend/INFO] OK, I'm done here.
[Boivin:Lazy:(2) 45.000000] [msg_process_suspend/INFO] Mmmh, I'm done now. Goodbye.
```

As you can see, the lazy_guy is still terminating its execution after 10 seconds, even if the dream master suspended it for 2 secs in between.

You could say that it's because I messed up with the amount of flops to execute in this task, but if you add the ```--log=simix_process.t:verbose```, the exec activity adds the following to the previous trace:
```
 [Boivin:dream_master:(1) 37.000000] [msg_process_suspend/INFO] Give a 2 seconds break to the lazy guy while he's working...
[37.000000] /home/mquinson/Code/simgrid/src/kernel/activity/SynchroExec.cpp:31: [simix_process/VERBOSE] This exec is suspended (remain: 784760000.000000)
[Boivin:dream_master:(1) 39.000000] [msg_process_suspend/INFO] Back to work, lazy guy!
[39.000000] /home/mquinson/Code/simgrid/src/kernel/activity/SynchroExec.cpp:38: [simix_process/VERBOSE] This exec is resumed (remain: 588570000.000000)
[Boivin:dream_master:(1) 39.000000] [msg_process_suspend/INFO] OK, I'm done here.
```

So, the remaining of the activity actually decreases while it's suspended. 

You could say that this is because for some reason you never reach the line turning the surf action's priority to 0 (https://github.com/simgrid/simgrid/blob/master/src/surf/surf_interface.cpp#L746) but it does.

So the problem lays within LMM and I'm stuck here. Some help would be appreciated. In the meanwhile, I commited the broken test, so we'll have some less green on the daemons. Sorry about this.

**Comment by fabienchaix** [comment]
Hi Martin,

Would you share the modifications you did so that I can run it (I guess they are trivial, but I am not familiar with MSG) ?

After a brief look at the code, I can suggest two tracks:

1) Perhaps the variable corresponding to this flow is already disabled (that I think we use to model initial latency). To check if this is so, please set a breakpoint at maxmin.cpp:1126. If the suspend call does not hit this line, this is our problem. In this case, we would have to consider increasing the initial latency with the suspend time

2) If the line is reached (and therefore disable_var() is called), it might be that I introduced a regression in the fixes I pushed in the beginning of the year . As a quick work around, you might try to run with --cfg=network/optim:Full to see if there is any difference.

**Comment by mquinson** [comment]
Hello (sorry for the latency -- too much teaching these days),

line maxmin.cpp:1126 is actually reached, and adding --cfg=cpu/optim:Full actually fixes the problem (model cpu, not network).

You can see the changes in examples/msg/process-suspend/process-suspend.c In particular, the test is added by commit d699aead00cdb6640cbc96582bd2defeb540b79a. In it, you can see that the ending date of the execution expected to be 47 (starting at 35 with a 2 second period in bewteen). But with cpu/optim:lazy, I get 45 because the task still progresses after the call to suspend...

Many many thanks for your help with that,
Mt

**Comment by fabienchaix** [comment]
Hi,
So the problem was that the function updateRemainingLazy was not called when the action is suspended. The LMM was giving the right results, but it was "invisible" to surf.

Thus the fix does not touch LMM, only surf_interface.cpp. Note that suspend has the specificity that we cannot estimate when it will end. Thus it does not seem appropriate to use the nextOccuringEventLazy method which is essentially trying to find when will be the next step. Instead I propose to call updateReaminingLazy from the suspend function. Here is the patch:

```
diff --git a/src/surf/surf_interface.cpp b/src/surf/surf_interface.cpp
index 01bc6f0..95c6ae7 100644
--- a/src/surf/surf_interface.cpp
+++ b/src/surf/surf_interface.cpp
@@ -744,9 +744,14 @@ void Action::suspend()
   XBT_IN("(%p)", this);
   if (suspended_ != 2) {
     lmm_update_variable_weight(getModel()->getMaxminSystem(), getVariable(), 0.0);
-    suspended_ = 1;
-    if (getModel()->getUpdateMechanism() == UM_LAZY)
+    if (getModel()->getUpdateMechanism() == UM_LAZY){
       heapRemove(getModel()->getActionHeap());
+      if (getModel()->getUpdateMechanism() == UM_LAZY  && stateSet_ == getModel()->getRunningActionSet() && priority_ > 0){
+        //If we have a lazy model, we need to update the remaining value accordingly
+        updateRemainingLazy(surf_get_clock());
+      }
+    }
+    suspended_ = 1;
   }
   XBT_OUT();
 }

```

I will now make a pull request for that.

Fabien

**Comment by mquinson** [comment]
Many thanks for the fix! If it helps, I can also simply apply this
patch. It would save you the pull request affaire. As you want.

Mt.

-- 
Being 37% better than a complete moron does not make you a genius.
             -- Bastard Reviewer From Hell

**Comment by mquinson** [comment]
So I picked your changes, crafted a commit done by your email, and integrated this commit. 

The bug is now fixed, and I'm really thankful for that.
