### ISSUE TITLE
s4u::Comm::async_recv():  void **data not set to any value?

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#144]
Here is a simple program in which a sender sends a pointer to an int to a receiver, and the receiver does an async_recv(..., void **data) followed by a wait().  After the wait() returns, data has not been set to any value. 
[mwe.zip](https://github.com/simgrid/simgrid/files/880616/mwe.zip)

**Comment by frs69wq** [comment]
Bon j'ai isolé d'où venait le problème, mais mon ordi s'est éteint car j'ai pas mon chargeur.
J'en discute avec Mt demain, ça devrait se régler assez vite je pense. 

Fred

Envoyé de mon iPhone

**Comment by mquinson** [comment]
Tomorrow will be a packed day for me :-(

**Comment by frs69wq** [comment]
The issue was in Comm::recv_async where setDstData was called with only one parameter (the adress of the destination buffer), but not giving it a size. Then when the data has to be effectively copied from the src buffer to the dst buffer, a test on the buffer size (has to be >0) fails and the copy is not done. This is fixed by commit 0e15d63

You may want to fix your cast in the mwe to XBT_INFO("DATA = %d", *(int*)data); to get the communicated value and not the integer version of the buffer address.

**Comment by mquinson** [comment]
Thanks Fred for fixing the issue. Thus closing the bug.
