### ISSUE TITLE
allow to personalize MC state equality

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#153]
It would be useful for the application to specify which memory locations should be compared for state equality, to make the MC check only a part of the application, and assume the rest is independent.

**Comment by mquinson** [comment]
Yeah, state abstraction may be useful here. I see that some parts of the code wanted to go in that direction: The entry point to the whole state comparison is `snapshot_compare()`:
https://github.com/simgrid/simgrid/blob/master/src/mc/compare.cpp#L1607

It takes a `state_comparator` as a singleton, which must be of type `simgrid::mc::StateComparator`. I think that we need to take the following steps to fix that bug:

  - [ ] Finish to flesh the `StateComparator` by integrating all the C functions still laying around as methods of that class. Some functions may need to be split in the process
  - [ ] Turn `StateComparator` into an interface, and make the current code a subclass called `StateComparatorFull` or something
  - [ ] Make the `StateComparator` a field of the checker instead of being a singleton deeply hidden. It seems to be mostly used in the `SafetyChecker` anyway.
  - [ ] Allow the user to provide their own StateComparator. For now, I'm not entierely sure of how we could do that without recompiling simgrid. Will see.

**Comment by mquinson** [comment]
I'm closing this, as there is no state equality anymore in SimGrid.
