### ISSUE TITLE
Weird negative refcount error with asynchronous communication...

### ISSUE THREAD

**Issue by henricasanova** [simgrid/simgrid#187]
Unless I am doing something wrong, I think there is a problem with waiting for asynchronous communications. I believe this bug was introduced in one of the relatively recent updates  to S4U... 

I am attaching a super short minimum working example. 

"make run" 
[mwe.zip](https://github.com/simgrid/simgrid/files/1066086/mwe.zip)

**Comment by mquinson** [comment]
Yeah, well, I got that problem too. The refcounting of activities is broken right now, but it should improve very soon. Sorry for the inconvenience.

**Comment by mquinson** [comment]
I confirm this bug to be fixed in my ongoing branch ActivityImplPtr.

I made an exhaustive test of point-to-point communication, and it works in this branch: https://github.com/simgrid/simgrid/blob/ActivityPtr/teshsuite/s4u/comm-pt2pt/comm-pt2pt.cpp

Unfortunately, many other things are still broken in this branch (such as waitany).

**Comment by mquinson** [comment]
I think that this bug is gone now, thus closing. Please reopen it if I'm wrong.
