### ISSUE TITLE
Error in the throughput of TCP transfer

### ISSUE THREAD

**Issue by bcamus** [simgrid/simgrid#219]
Hello,

As discussed previously here is my example.

When taking a look at line 308 (see below) of the execution trace, we see that the transfer get a throughput of 115476190 B/sec, but the expected throughput is 0.97 * 125000000 = 121250000 B/sec.

`[surf_kernel/DEBUG] Action(0x7fcc42c4d6f0) Start 0.000000. May finish at 37.222804 (got a share of 115476190.476190). Max_duration -1.000000
`

We can see in line 296 (see below) that the cross-traffic effect is considered in the  LMM even if only one flow is active.

`[surf_maxmin/DEBUG] (0.050000.'2'(115476190.476190) + 1.000000.'2'(115476190.476190) + 0) <= 121250000.000000 ('4')
`

[SimGrid-BugReport-bandwidth.zip](https://github.com/simgrid/simgrid/files/1264523/SimGrid-BugReport-bandwidth.zip)

**Comment by mquinson** [comment]
Discussing again with @bcamus the problem is that in his setting, he cannot explain the prediction of SimGrid. We should check again, and that may be either a bug or a documentation issue. 
The used model is not perfectly clear from the logs, but from his memory, that's just the default setting. So I am wondering whether the default model and its 13 times bigger latency could be the explanation. 
I need to further investigate.

**Comment by frs69wq** [comment]
the difference between the expected and traced values is of about 5% so it sounds like cross-traffic as mentioned by @bcamus in the initial message. 
Unless I'm wrong, having a single flow doesn't prevent you to be it by cross-traffic. It just means that the model takes the ACKs traveling back from destination to source into account. 

Then, the observed value might in fact make perfect sense ... @alegrand do you confirm?

**Comment by alegrand** [comment]
Hi,

Indeed, the .97 (rough payload incurred by TCP) and the .05 additional consumption  (rough estimate incurred by acks) add together when the same (non full-duplex) link is used. I do not know much about such links nowadays, except maybe for WIFI where the channel acts as a bus. This would disappear if you used full-duplex link in your platform. 

Note that the .97 and the .05 are crude estimates and should not be considered as "universal" values. They depend on  the TCP configuration and should be adjusted if you want super precise estimates. The difference is likely to be visible when comparing to NS simulations but ... they're both approximations of the real world. So I would not consider this like an error but rather like a normal but surprising and not really documented behavior.

Hope this helps...

   Arnaud

**Comment by frs69wq** [comment]
This is a documentation issue then. I think this behavior is described in the TOMACS paper on the network models, but not in the doc on line. Especially the cross traffic thing that has been added later in the default model.

**Comment by mquinson** [comment]
Just to say, "full-duplex" were renamed to "split duplex" because networking people would have a hearth attack on the naming of "full duplex" for something that is ... actually 2 links with each of them being usable in both directions if you don't pay attention.
Beside of that, we should probably add a "Understanding the modeling of TCP" at the bottom of https://simgrid.frama.io/simgrid/platform_howtos.html Any volunteer?

**Comment by frs69wq** [comment]
The behavior of the default TCP model of Simgrid is now explained on a simple example similar to that of this issue in the online documentation:  https://simgrid.frama.io/simgrid/platform_howtos.html#understanding-the-default-tcp-model
@bcamus could you tell if it answers your concerns about the model expressed in this issue?

**Comment by bcamus** [comment]
Yes, this example completely answers all my concerns. Thank you !
