### ISSUE TITLE
process migration between VMs

### ISSUE THREAD

**Issue by qazxiaye** [simgrid/simgrid#245]
Hello,

An issue is found when a process deployed in a VM is migrated to another VM. The process still has the same CPU capacity obtained from the original VM (capping defined in the source VM) even when the destination VM does not have so much CPU. 
[test-MigProcInVM.zip](https://github.com/simgrid/simgrid/files/1498837/test-MigProcInVM.zip)

A working example is attached. There are two deployment files (deploy1.xml & deploy2.xml), these two deployments should give the same simulation result if this issue is fixed.

**Comment by mquinson** [comment]
Hello,

this bug is much harder to fix that I first thought, sorry for the delay. There is no support underneath for the migration of activities, and I'm a bit dubious about the semantic we want here. I write my thoughts here just to gather them, and gather feedback if possible.

First, I need to relocate the activities. Ie, add a ExecImpl::migrate(Host*). I think I'll have to create a new surf object on the new host, taking care not to lose any information (the initial amount of work so that the ratio is still correct) and destroy the previous one.
For communications, I probably need a migrateSrc() and migrateDst(), or a migrate(from, to).

Then, I need to use these functions in process->migrate(). I will only migrate the activity the process is blocked onto. It's easy to mess up things about asynchronous activities: some may have been started as remote executions (see examples/s4u/exec-remote/s4u-exec-remote.cpp). So the user will have to take care of their asynchronous activities by themselves.

**Comment by mquinson** [comment]
Ok, it is now possible to call setHost() on a s4u::Exec after its start (but before its termination). This is the first step toward the resolution of this bug. I'll try to do the same for communications soonish.

**Comment by mquinson** [comment]
Well. Doing the same for communications is too hard in the current state of the code. I'll postpone it as it is not needed to fix the bug you were experiencing. Please open another bug (with another MWE) if you actually need communications. But to be honnest, I hope you wont need it right away...
