### ISSUE TITLE
Deprecate all functions in smpi_dvfs.cpp

### ISSUE THREAD

**Issue by Shurakai** [simgrid/simgrid#278]
These functions seem to be a convenience layer. However, the name `smpi_get_host_power_peak_at` doesn't really tell me that it's the current actor's host that we're looking at. So we should at least rename them. However, I believe that user's will be better off by just using `host->get_pstate_speed(pstate)` instead. It's a bit more verbose but makes the code more readable as the purpose of all these functions is just to hide `sg_host_self()`.

So, I think a deprecation would be the right way to clean up this part of SMPI.

**Comment by mquinson** [comment]
Why should we deprecate the C wrappers?

**Comment by Shurakai** [comment]
Why would that imply removing `smpicc`?

`smpi_set_host_pstate(pstate_index)` is the same as `sg_host_set_pstate(sg_host_self(), pstate_index)`, which is already available in C (at least sg_host_self() is in host.h).

What I'm saying is that there's no need to provide SMPI-specific (!!) functions that only save you a few keystrokes but would be valid for other modules as well. 

For instance, what makes the following so SMPI specific that they are defined in SMPI?

```C++
void smpi_set_host_pstate(int pstate_index)
{
  sg_host_set_pstate(sg_host_self(), pstate_index);
}
/** @brief Gets the pstate at which the processor currently running */
int smpi_get_host_pstate() {
  return sg_host_get_pstate(sg_host_self());
}
```
I strongly believe that it is reasonable to have a user use

```C++
sg_host_set_pstate(sg_host_self(), pstate_index);
```
directly.

If you insist on keeping this shortcut, please move it out of SMPI because it shouldn't bloat SMPI.

**Comment by mquinson** [comment]
Indeed, that's not the C wrapper you want to remove, my bad. I got confused because your first replacement was in C++.

My feelings about having a SMPI wrapper over the sg things are not so strong. In my mind, `smpi_set_host_pstate(pstate_index)` feels more MPI-ish than `sg_host_set_pstate(sg_host_self(), pstate_index)` that requires you to know about SMPI internals. But if it's important to you, please proceed and install some deprecation compatibility wrappers.

**Comment by Shurakai** [comment]
Thanks, this has been done in 51b3df03e813ceb19bdcbc8564a2529dab183325
