### ISSUE TITLE
Alltoall collective implementation of mpich

### ISSUE THREAD

**Issue by TruongThaoNguyen** [simgrid/simgrid#294]
Hi
I would like to understand the implementation of MPI alltoall collective algorithm of MPICH. I found that the implementation of this library in Simgrid may incorrect in the case of long message. I use the Simgrid version 3.19.
In the file smpi_mpich_selector.cpp, the comment lines quoted that
>   For long messages and power-of-two number of processes, we use a
>    pairwise exchange algorithm, which takes p-1 steps. We
>    calculate the pairs by using an exclusive-or algorithm:
>            for (i=1; i<comm_size; i++)
>                dest = rank ^ i;

However the codes in line 166 show that
```
    if ((block_dsize < short_size) && (communicator_size >= 8)) {
        return Coll_alltoall_bruck::alltoall(sbuf, scount, sdtype, rbuf, rcount, rdtype, comm);
    } else if (block_dsize < medium_size) {
        return Coll_alltoall_basic_linear::alltoall(sbuf, scount, sdtype, rbuf, rcount, rdtype, comm);
    }else if (communicator_size%2){
        return Coll_alltoall_ring::alltoall(sbuf, scount, sdtype, rbuf, rcount, rdtype,comm); // <-- MAY WRONG 
    }
    return Coll_alltoall_ring::alltoall (sbuf, scount, sdtype, rbuf, rcount, rdtype, comm);
```
I think it for the case of long message and power-of-two processes, it should call
`Coll_alltoall_pair_rma::alltoall(sbuf, scount, sdtype, rbuf, rcount, rdtype,comm);`

**Comment by adegomme** [comment]
Hi,

As stated in http://simgrid.gforge.inria.fr/simgrid/latest/doc/group__SMPI__API.html#SMPI_use_colls the logic is taken from the one found in mpich 3.0.4 and has not been updated since. The comments were also taken from it.

At the time, it was quite messy in the implementation : https://github.com/pmodels/mpich/blob/v3.0.4/src/mpi/coll/alltoall.c and I may have missed some things.
But indeed for power of two and long messages, pair is being used (not pair_rma though). I will push a fix asap. Thanks for the report.

Anyway, an update of these collective implementations should actually be done in order to match current implementations, as https://github.com/pmodels/mpich/blob/master/src/mpi/coll/alltoall/alltoall.c is the new version, and much more clean than 5 years ago.
