### ISSUE TITLE
How to add disks in clustered platform? 

### ISSUE THREAD

**Issue by zeus-cht** [simgrid/simgrid#390]
Hi!
I know I can add a **disk** tag in the **host** tag when I want to add disks in my hosts. But I wonder what should I do if I want to add disks for all host in a **cluster**  tag? (such as the **dragonfly** cluster  `examples/platforms/cluster_dragonfly.xml` :
``` xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">
<platform version="4.1">
  <zone id="world" routing="Full">
    <cluster id="bob_cluster" topology="DRAGONFLY" topo_parameters="3,4;4,3;5,1;2"
             prefix="node-" radical="0-119" suffix=".simgrid.org"
	     speed="1Gf" bw="125MBps" lat="50us"
             loopback_bw="100MBps" loopback_lat="0" limiter_link="150MBps"/>
  </zone>
</platform>
```
To be more precise, how to add disks in the cluster xml file? 
Or rather, it can only be achieved through source C code using `#include <simgrid/s4u.hpp>`? like `s4u::Host.create_disk()`?
Maybe this is a naive question, please forgive me.
 Best regards.

**Comment by mquinson** [comment]
Hello,

I think that you are searching for this function: https://simgrid.frama.io/simgrid/app_s4u.html#_CPPv4N7simgrid3s4u4Host11create_diskERKNSt6stringEdd ie Host::create_disk()

You were speaking of it in your report, so maybe you are having difficulties to use that? You have examples in examples/cpp/io-degradation/s4u-io-degradation.cpp or its python counterpart, and also examples/cpp/io-disk-raw/s4u-io-disk-raw.cpp

I'm closing this bug report because I think it solves your request. Please feel free to reopen the bug if I'm wrong.
