### ISSUE TITLE
There should be a default logging channel

### ISSUE THREAD

**Issue by mquinson** [simgrid/simgrid#77]
By default, every logging done using XBT is directed to the following category variable:

```static s_xbt_log_category_t *_simgrid_log_category__default```

Then, the ```XBT_LOG_NEW_DEFAULT_CATEGORY(blahblah)``` macro does the following (resulting in creating a blahblah log category, to which every logs are directed):
```
s_xbt_log_category_t _simgrid_log_category__blahblah = {inline initializer};
static s_xbt_log_category_t *_simgrid_log_category__default = &_simgrid_log_category__blahblah;
```

We should declare a weak ```_simgrid_log_category__default``` symbol collecting all logs from the files where no specific logging channel is declared. It would be nicer to the users to not expose them to that complexity right away.

I'm however not completely sure that it would actually do the trick. On all platforms. 

@randomstuff what do you think?

**Comment by randomstuff** [comment]
I guess this would not work because we woud declare `_simgrid_log_category__default` once global with weak binding and one as `static` and this would break the one definition rule. Moreover STB_WEAK is only meaninful inside a module (shared-object/executable). It would be nice to have a default default logging channel but I'm not sure how this could be achieved.

**Comment by mquinson** [comment]
Damn. That's too bad. If we cannot think of a (potential) solution, I guess we should close the issue...

**Comment by mquinson** [comment]
It seems impossible to implement right now, thus closing.
