### ISSUE TITLE
simgrid does not compile

### ISSUE THREAD

**Issue by rriemann** [simgrid/simgrid#92]
Hello,

I tried to compile your project on an up-to-date opensuse Leap_42.1/x86_64 maschine and got a boost context related compile error.

The disribution comes with
- gcc v4.8
- libboost context v1.58.0

I eventually resoved the problem by upgrading to gcc v6 and libboost v1.60. Hence, I use the smartgrid context API v2 now.

Is this known behaviour? If so, please mention this in the install from source notes.

**Comment by adegomme** [comment]
Hello,

What was the error exactly ? And which version of SimGrid were you using  (if from git, please tell the last commit id) ?
Because 4.8 + older boost_context libraries are tested and should work, even if not on suse (see https://ci.inria.fr/simgrid/job/SimGrid-Multi/ for the tested configurations).

**Comment by rriemann** [comment]
I'm on master: 71980d9754a6693a769dce2f1e55d92103b46b5e

Unfortunately, I cannot reproduce the error right now without de/re-installing all of gcc and boost.

The principle error (google search extract) was: `"invalid use of ‘boost::context::fcontext_t"`

**Comment by rriemann** [comment]
I will see if I can create opensuse rpms in the next days to come. Then, I should get again the error.

**Comment by adegomme** [comment]
I did setup an opensuse builder, and am able to reproduce your issue ( https://ci.inria.fr/simgrid/job/SimGrid-Multi/build_mode=Debug,node=simgrid-opensuse-42-64/3448/console )

from /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-opensuse-42-64/build/SimGrid-3.13.90/src/simix/ContextBoost.cpp:12:
15:30:44 /usr/include/boost/context/execution_context.hpp:202:52: error: 'std::index_sequence' has not been declared

Thanks for the report

**Comment by adegomme** [comment]
std::index_sequence is a C++14 feature. This was not supported in gcc 4.8. So using a recent (1.58 is from 2015) boost with an old (4.8 dates from 2011) compiler seems to be the issue here, indeed.

It seems to be a known issue with 1.58, actually : http://lists.boost.org/boost-users/2015/04/84110.php 

So I would advise to keep your upgraded versions, and close this, as this is not on our end. We could add a check in this particular case, but we try to avoid adding too many specific cases on our already messy cmake files.

**Comment by rriemann** [comment]
Wow. Thank you for your answer. I suggest to mention at some place a recommendation for gcc/boost version in the docs, e.g. [here](http://simgrid.gforge.inria.fr/simgrid/3.14/doc/install.html#install_src).

I have some other questions, but that's for the mailing list. See you over there! :)

**Comment by mquinson** [comment]
You can also come and say hello on IRC: http://simgrid.gforge.inria.fr/simgrid/3.14/doc/community_contact.html

**Comment by randomstuff** [comment]
Well actually this is not our fault, this seems to be a bug of Boost which should compile correctly without C++14 support.
